### ISSUE TITLE
Please support qmlls.

### ISSUE THREAD

**Issue by HangZhouCat** [SublimeText/QML#29]
Qt has provided a language server since 6.2, please support it.

**Comment by deathaxe** [comment]
Language servers are normal command line programs.

Any language server can be adopted using [LSP](https://github.com/sublimelsp/lsp) package.

All it needs is a client configuration (see: https://lsp.sublimetext.io/client_configuration)

Alternatively, a related `LSP-qml` helper package could be created to do the configuration job automatically.

That's out of scope for this syntax definition package.

**Comment by HangZhouCat** [comment]
> https://lsp.sublimetext.io/client_configuration

Okay, thank you. Forgive me for asking a stupid question.

**Comment by deathaxe** [comment]
It's a valid request - just not within scope here.

**Comment by ratijas** [comment]
To be fair, the package is named simply "QML", not "QML Syntax" or anything more specific, so from a user perspective it would be somewhat reasonable to except it to provide the LSP configuration and other IDE experiences, especially in the absence of any package named like "LSP-qml".

Personally I don't rely on qmlls just yet, because it is not stable or usable enough for my KDE workflow just yet (such as modules based on non-declarative type registration aren't picked up by qmlls), but hopefully things will improve in the future.
